Feature/#104
B8ND-winter-project/alimo-web pull request #109
Opened 2024-03-15 03:47 UTC by ftery0

2024-03-15 13:24 UTC, Sanghyun0505 requested changes
다른 선배들께 코드리뷰 받아보시고 다시 요청해주세요. 

콘솔 삭제, 전체적인 lint를 적용해주시고 카멜케이스가 안되어 있는 함수나 변수들을 수정해주세요.
그리고 불필요한 useState들이 몇몇개 있습니다. state를 최소화하는 법을 고민해보시면 좋을 것 같습니다. 
서버 통신 로직같은 경우에도 폴더를 따로 나눠서 구성해보시는 걸 추천합니다.

2024-03-15 13:24 UTC, Sanghyun0505 commented on src/components/Profile/ProfileAlert.tsx
>    };
onOpen() 함수를 호출하는 함수를 굳이 만들필요는 없을 것 같습니다. onClick에 바로 담아주세요

2024-03-15 13:24 UTC, Sanghyun0505 commented on src/util/Sidebar/useSideBarNavigation.tsx
>          case "/write-read":
useSideBarNavigation은 customHooks이기에 hooks 폴더로 옮겨주세요

2024-03-16 03:12 UTC, BaekSeungHa approved these changes
pr 올릴 때 무슨 작업 했는지 작성해주세요 상현이가 해놔서 딱히 리뷰 할건 없는것 같습니다

2024-03-16 03:12 UTC, BaekSeungHa commented on src/repository/token/token.repository.ts
> +console.log("reost");
콘솔 지워주세요

2024-03-16 03:12 UTC, BaekSeungHa commented on src/Hooks/auth/useLogout.ts
> +const UseLogout = () => {
```suggestion
const useLogout = () => {
```

2024-03-16 03:12 UTC, BaekSeungHa commented on src/lib/axios/customAxios.ts
> +export const Alimov1Axios = createAxiosInstance({
```suggestion
export const alimoV1Axios = createAxiosInstance({
```

2024-03-17 08:39 UTC, ftery0 commented on src/components/Profile/ProfileAlert.tsx
>    };
넵 고치겠습니다

2024-03-17 08:41 UTC, ftery0 commented on src/lib/PrivateRoute.tsx
> +export default PrivateRoute;
custom hooks으로 해볼 생각을 안해봤습니다... 한번 해보겠습니다!

2024-03-17 08:41 UTC, ftery0 commented on src/Hooks/Sidbar/useSiebar.tsx
> +  const [Name, setName] = useState<string>("");
넵 감사합니다 고치겠습니다

2024-03-17 08:44 UTC, ftery0 commented on src/Hooks/Sidbar/useSiebar.tsx
>    const [Category, setCategory] = useState<string[]>([]);
넵 수정하겠습니다

2024-03-17 08:49 UTC, ftery0 commented on src/util/Sidebar/useSideBarNavigation.tsx
>          case "/write-read":
넵 변경하겠습니다

2024-03-17 08:52 UTC, ftery0 commented on src/repository/token/token.repository.ts
> +console.log("reost");
넵

2024-03-17 23:27 UTC, ftery0 commented on src/Hooks/Sidbar/useSiebar.tsx
>      );
넵 좋은 피드백 감사합니다 수정하겠습니다

2024-03-19 01:00 UTC, Sanghyun0505 approved these changes

2024-03-19 10:52 UTC, wjzlskxk commented on src/Hooks/auth/useLogin.ts
> +      const koreanRegex = /[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]/; // 한글을 포함하는 정규식
기존 로직상 아이디에 영어랑 숫자만 입력되게 해놓았는데 굳이 한글 정규식으로 막아야할 이유가있나요?

2024-03-19 11:01 UTC, wjzlskxk commented on src/Hooks/auth/useLogin.ts
> +      const koreanRegex = /[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]/; // 한글을 포함하는 정규식
+ 추가로 에러바운더리메시지 왼쪽으로 살짝만 밀어주세요..😁

2024-03-19 11:21 UTC, merged